### ISSUE TITLE
how to make it to support chinese? 

### ISSUE THREAD

**Issue by wuzhiye7** [rgeoghegan/markdown-live#2]
hi,how to make it to support chinese?

**Comment by rgeoghegan** [comment]
It should support any utf-8 markdown text. What issues are you seeing?

**Comment by wuzhiye7** [comment]
@rgeoghegan   
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8. 
so i modified your code with chardet decoding ,and the error disappeared ,
but the web page is not right chinese.
![image](https://user-images.githubusercontent.com/20206364/42299869-1b8bbdf0-8040-11e8-8b71-04699e4af164.png)

**Comment by wuzhiye7** [comment]
@rgeoghegan  solved it !  i add charset to the head.thanks also.
![image](https://user-images.githubusercontent.com/20206364/42301099-366d3d00-8046-11e8-8e10-446d4b407977.png)
